export const config = {
  formSelector: ".modal__form",
  inputSelector: ".modal__input",
  submitButtonSelector: ".modal__save-button",
  cardsContainerSelector: "#cards-list",
  cardViewModalSelector: "#card-view-modal",
  inputIdCardSelector: "#input-id-card",
  buttonDeleteSelector: ".card__delete-button",
  plusButtonSelector: ".profile__add-button",
  profileEditButtonSelector: ".profile__edit-button",
  avatarEditButtonSelector: ".avatar__edit-button",
  inactiveButtonClass: "modal__save-button_disabled",
  inputErrorClass: "modal__input_type_error",
  errorClass: "modal__error",
  errorClassVisible: "modal__error_visible",
};
